### ISSUE TITLE
Styling and Responsive Design

### ISSUE THREAD

**Issue by berry1104** [Ishi01/CITS5505Group41Project#12]
Develop a consistent styling theme that is responsive on mobile devices 
- [x] Develop a Master CSS File:
  - [x] Define common styles for body, headers, and footers.
  - [x] Set global font families, sizes, and colors.
  - [x] Standardize UI components like buttons and forms.

- [x] Page-Specific CSS:
  
  
- [x] Responsive Design:

**Comment by stuar7** [comment]
Complete with #41
