### ISSUE TITLE
Implement Dynamic Leaderboards

### ISSUE THREAD

**Issue by berry1104** [Ishi01/CITS5505Group41Project#13]
Develop a leaderboard system that dynamically updates to reflect user scores and rankings based on their interactions and outcomes.

- [x] API for Retrieving Leaderboard Data:
  

- [x] Frontend Implementation:
  - [x] Design a leaderboard page that displays user ranks, scores, and usernames.
  - [x] Implement asynchronous data fetching to keep the leaderboard updated in real-time.

**Comment by cloud9ight** [comment]
Basic functions done, need to update

**Comment by cloud9ight** [comment]
Dynamic Leaderboards completed, works well to catch and show all the data. Also linked to the user page
