### ISSUE TITLE
Migrate Quiz Questions from JSON to Database

### ISSUE THREAD

**Issue by berry1104** [Ishi01/CITS5505Group41Project#15]
Description: Transition the storage of quiz questions from static JSON files to our database system
- [x] Create QuizQuestions Table
  

- [x] **Develop Import Script**:
  - Write a script to parse JSON and insert data into the database.
  - Handle data format inconsistencies and database errors.

- [x] **Test Import Process**:
  - Conduct initial tests with a subset of JSON data.
  - Check data integrity and correct any errors.

- [x] **Update Quiz Logic**:
  - Modify the quiz fetching logic to use the database.
  - Ensure smooth transition without user disruption.

**Comment by stuar7** [comment]
Completed in #26
