### ISSUE TITLE
Fourth Deliverable Product

### ISSUE THREAD

**Issue by stuar7** [Ishi01/CITS5505Group41Project#36]
### Objective
This deliverable implements features that allow the viewing of game data and management. That is, leaderboards, user history, admin account management page. The periodic table page has also been updated to work.

This deliverable also includes some basic testing methodologies to prepare for the next deliverable.

### Features

1. **Periodic Table**
   - [x] Updated to work with latest database and routing methods.

2. **User**
   - [x] Create a user page that shows the history of games played.

3. **Leaderboard**
   - [x] Create a leaderboard page that shows the top performance for each game.

4. **Admin**
   - [x] Creates an admin user that can modify the database directly through a manage page.

5. **CSS Improvements**
   - [x] All new pages are appropriately stylised.

### Completion Criteria
This deliverable is considered complete if all features are tested and implemented.

**Comment by cloud9ight** [comment]
Dynamic leaderboard fetchs and demonstrates data in real time (tested)
Matched CSS styling added to pages
Periodic Table updated with question and a simple rating system added

**Comment by stuar7** [comment]
Almost complete in #39. Some CSS adjustments still need to be made as there were conflicting stylesheet changes made by three people. I've divided the css into different sheets to make following the styles easier.

**Comment by stuar7** [comment]
Marking as complete as #39 finished this. Minor improvements can be shipped with last deliverable.
